name: Blog Deploy
on:
  push:
    branches:
      - blog
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: blog
          BRANCH: master
          FOLDER: build
          BUILD_SCRIPT: yarn install && yarn build
